version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    image: mutations-fork/contentful-migrate
    volumes:
      - .:/app
      - node_modules:/app/node_modules:delegated
    working_dir: /app
volumes:
  node_modules:
